kind: Service
apiVersion: v1
metadata:
  name: simple-hello-world-svc
spec:
  selector:
    name: simple-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 80
  type: LoadBalancer
